In [1]:
import numpy as np
import random
import graph

In [2]:
pages, links = 100, 250  #map(int,input().split())
epsilon = 1e-4
d = 0.85
iterations = 10000000
assert links <= 2*pages*pages
assert d <= 1

In [3]:
def mapper_mult(adjacencyFunction, pageRank):
    intermediate = {}
    for i in range(pageRank.shape[0]):
        for j in range(pageRank.shape[0]):
            key = str(i)
            if key in intermediate.keys():
                intermediate[key].append("A,{},{}".format(j,adjacencyFunction[i,j]))
            else:
                intermediate[key]=["A,{},{}".format(j,adjacencyFunction[i,j])]
    
    for i in range(pageRank.shape[0]):
        key = str(i)
        intermediate[key].append("P,{},{}".format(i,pageRank[j]))
#         print("Adding Key:")
    
#     print("intermediate: {}".format(intermediate))
    
    return intermediate

In [4]:
def reducer_mult(intermediate):
    AVals = {}
    PVals = {}
    for i in intermediate:
        val_arr = intermediate[i]
#         print("val_arr: {}".format(val_arr))
        for j in val_arr:
            mat, ind, val = j.split(',')
            ind = int(ind)
            val = float(val)
            if mat == 'A':
                if int(i) in AVals.keys():
                    AVals[int(i)].append((ind,val))
                else:
                    AVals[int(i)]=[(ind,val)]
            else:
                PVals[ind] = val
#     print("AVals: {}".format(AVals))
#     print("PVals: {}".format(PVals))
    
    reduced = {}
    for i in AVals:
        val_arr = AVals[i]
        reduced[i] = (1-d)/pages
        for j in val_arr:
            reduced[i] += j[1] * PVals[j[0]]
            
    return reduced

In [5]:
pageGraph = np.zeros(shape=(pages,pages))

In [6]:
for i in range(links):
    x,y = graph.genEdges(0,pages-1,pageGraph)
    pageGraph[x,y] = 1
pageGraph

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
outLinks = graph.getOutDegree(pageGraph)
print(outLinks)

[2. 1. 3. 2. 6. 4. 0. 3. 5. 4. 2. 0. 0. 1. 4. 3. 7. 3. 3. 4. 4. 2. 3. 4.
 3. 1. 1. 3. 3. 3. 3. 2. 2. 0. 2. 1. 2. 2. 3. 4. 1. 1. 3. 4. 2. 3. 5. 3.
 4. 1. 0. 3. 0. 3. 3. 2. 3. 2. 3. 4. 2. 2. 4. 2. 3. 3. 2. 0. 3. 6. 1. 1.
 5. 4. 6. 4. 2. 2. 2. 0. 2. 3. 1. 1. 0. 0. 1. 1. 6. 2. 2. 1. 2. 1. 1. 3.
 4. 3. 1. 3.]


In [8]:
pageRank = np.zeros(shape=(pages)) + 1/pages
print(pageRank)

[0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01]


In [9]:
adjacencyFunction = graph.getAdjacencyFunction(pageGraph)
print(adjacencyFunction)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
for i in range(iterations):
    pageRankNew = reducer_mult(mapper_mult(adjacencyFunction, pageRank))
#     print(pageRankNew)
    temp = np.zeros(shape=pageRank.shape)
    for j in pageRankNew: temp[j] = pageRankNew[j]
    if np.allclose(temp,pageRank, atol=epsilon, rtol=0.0):
        print(i)
        break
    pageRank = temp
    print(pageRank)

[0.01233333 0.0015     0.004      0.01066667 0.0065     0.00483333
 0.01209524 0.0215     0.0015     0.00483333 0.0035     0.0015
 0.02983333 0.01016667 0.01483333 0.01183333 0.00483333 0.01683333
 0.00483333 0.004      0.02266667 0.00816667 0.00983333 0.0105
 0.00983333 0.0135     0.01483333 0.0115     0.0065     0.00983333
 0.01316667 0.0065     0.01733333 0.0015     0.0065     0.0135
 0.01816667 0.014      0.014      0.01566667 0.006      0.00683333
 0.01042857 0.0015     0.01292857 0.0015     0.004      0.00816667
 0.00316667 0.0087619  0.01816667 0.0065     0.00733333 0.0015
 0.0065     0.01816667 0.01316667 0.02733333 0.00742857 0.01733333
 0.01316667 0.0115     0.019      0.01983333 0.01733333 0.00733333
 0.0115     0.0115     0.009      0.0065     0.0115     0.01316667
 0.0115     0.009      0.0112619  0.0115     0.0115     0.0065
 0.004      0.01066667 0.019      0.01066667 0.004      0.004
 0.01316667 0.01516667 0.01066667 0.01483333 0.01066667 0.0137619
 0.0115     0.0085   

[0.00843382 0.0015     0.00310011 0.00736708 0.00470023 0.00363348
 0.00828143 0.0143009  0.0015     0.00363348 0.00278009 0.0015
 0.01963461 0.00704706 0.01003394 0.0081138  0.00363348 0.01131403
 0.00363348 0.00310011 0.01504762 0.00576697 0.00683371 0.00726041
 0.00683371 0.00918054 0.01003394 0.00790045 0.00470023 0.00683371
 0.00896719 0.00470023 0.01163405 0.0015     0.00470023 0.00918054
 0.01216742 0.00950056 0.00950056 0.01056731 0.0043802  0.00491357
 0.00721469 0.0015     0.0088148  0.0015     0.00310011 0.00576697
 0.00256674 0.00614795 0.01216742 0.00470023 0.0052336  0.0015
 0.00470023 0.01216742 0.00896719 0.0180345  0.00529455 0.01163405
 0.00896719 0.00790045 0.01270079 0.01323416 0.01163405 0.0052336
 0.00790045 0.00790045 0.00630034 0.00470023 0.00790045 0.00896719
 0.00790045 0.00630034 0.00774806 0.00790045 0.00790045 0.00470023
 0.00310011 0.00736708 0.01270079 0.00736708 0.00310011 0.00310011
 0.00896719 0.01024728 0.00736708 0.01003394 0.00736708 0.00934817
 0.0

In [11]:
print(pageRank)

[0.00813726 0.0015     0.00303168 0.00711615 0.00456335 0.00354224
 0.00799139 0.01375341 0.0015     0.00354224 0.00272534 0.0015
 0.018859   0.00680981 0.00966894 0.00783093 0.00354224 0.01089428
 0.00354224 0.00303168 0.01446819 0.00558447 0.00660559 0.00701403
 0.00660559 0.00885205 0.00966894 0.00762671 0.00456335 0.00660559
 0.00864782 0.00456335 0.01120062 0.0015     0.00456335 0.00885205
 0.01171118 0.00915838 0.00915838 0.0101795  0.00425702 0.00476758
 0.00697027 0.0015     0.00850195 0.0015     0.00303168 0.00558447
 0.00252112 0.00594916 0.01171118 0.00456335 0.00507391 0.0015
 0.00456335 0.01171118 0.00864782 0.01732732 0.00513226 0.01120062
 0.00864782 0.00762671 0.01222173 0.01273229 0.01120062 0.00507391
 0.00762671 0.00762671 0.00609503 0.00456335 0.00762671 0.00864782
 0.00762671 0.00609503 0.00748083 0.00762671 0.00762671 0.00456335
 0.00303168 0.00711615 0.01222173 0.00711615 0.00303168 0.00303168
 0.00864782 0.00987316 0.00711615 0.00966894 0.00711615 0.00901251
 0.

In [12]:
reducer_mult(mapper_mult(adjacencyFunction, pageRank))

{0: 0.008102948144078257,
 1: 0.0015000000000000002,
 2: 0.0030237572640180593,
 3: 0.007087109968066217,
 4: 0.004547514528036119,
 5: 0.0035316763520240792,
 6: 0.007957828404647965,
 7: 0.013690058112144476,
 8: 0.0015000000000000002,
 9: 0.0035316763520240792,
 10: 0.002719005811214448,
 11: 0.0015000000000000002,
 12: 0.01876924899220467,
 13: 0.006782358515262606,
 14: 0.009626705408096316,
 15: 0.0077981966912746455,
 16: 0.0035316763520240792,
 17: 0.010845711219310765,
 18: 0.0035316763520240792,
 19: 0.0030237572640180593,
 20: 0.014401144835352903,
 21: 0.005563352704048158,
 22: 0.006579190880060198,
 23: 0.006985526150465014,
 24: 0.006579190880060198,
 25: 0.008814034867286685,
 26: 0.009626705408096316,
 27: 0.007595029056072238,
 28: 0.004547514528036118,
 29: 0.006579190880060198,
 30: 0.008610867232084277,
 31: 0.004547514528036118,
 32: 0.011150462672114374,
 33: 0.0015000000000000002,
 34: 0.004547514528036119,
 35: 0.008814034867286685,
 36: 0.011658381760120396,
 